

x-airflow-common: &airflow-common
  image: apache/airflow:2.7.1
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - API_KEY=${API_KEY}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./requirements.txt:/requirements.txt
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
      <<: *airflow-common
      entrypoint: /bin/bash
      command: >
        -c "pip install -r /requirements.txt &&
            airflow db init || true &&
            airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
      restart: on-failure

  airflow-webserver:
      <<: *airflow-common
      command: webserver
      ports:
        - "8080:8080"
      restart: always
      depends_on:
        - airflow-init

  airflow-scheduler:
      <<: *airflow-common
      command: scheduler
      restart: always
      depends_on:
        - airflow-init

volumes:
  postgres-db-volume: